services:
  - type: web
    name: movie-recommender
    env: python
    buildCommand: "./setup.sh"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
